//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nRage.Tests.Unit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nRage.Tests.Unit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;show id=&apos;5481&apos;&gt;&lt;name&gt;Teenage Mutant Ninja Turtles (1987)&lt;/name&gt;&lt;link&gt;http://www.tvrage.com/Teenage_Mutant_Ninja_Turtles_1987&lt;/link&gt;&lt;started&gt;1988-10-01&lt;/started&gt;&lt;ended&gt;1996-11-00&lt;/ended&gt;&lt;country&gt;USA&lt;/country&gt;&lt;status&gt;Canceled/Ended&lt;/status&gt;&lt;classification&gt;Animation&lt;/classification&gt;&lt;genres&gt;&lt;genre&gt;Animation General&lt;/genre&gt;&lt;genre&gt;Action&lt;/genre&gt;&lt;genre&gt;Adventure&lt;/genre&gt;&lt;/genres&gt;&lt;airtime&gt;Saturday&lt;/airtime&gt;&lt;runtime&gt;30&lt;/runtime&gt;&lt;episode&gt;&lt;number&gt;02x13&lt;/number&gt;&lt;title&gt;Return of the Technodrome&lt;/title&gt;&lt;airdate&gt;1988-12-0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RESPONSE_EPISODEINFO_5481_2x13 {
            get {
                return ResourceManager.GetString("RESPONSE_EPISODEINFO_5481_2x13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;show id=&apos;5481&apos;&gt;&lt;name&gt;Teenage Mutant Ninja Turtles (1987)&lt;/name&gt;&lt;link&gt;http://www.tvrage.com/Teenage_Mutant_Ninja_Turtles_1987&lt;/link&gt;&lt;started&gt;1988-10-01&lt;/started&gt;&lt;ended&gt;1996-11-00&lt;/ended&gt;&lt;country&gt;USA&lt;/country&gt;&lt;status&gt;Canceled/Ended&lt;/status&gt;&lt;classification&gt;Animation&lt;/classification&gt;&lt;genres&gt;&lt;genre&gt;Animation General&lt;/genre&gt;&lt;genre&gt;Action&lt;/genre&gt;&lt;genre&gt;Adventure&lt;/genre&gt;&lt;/genres&gt;&lt;airtime&gt;Saturday&lt;/airtime&gt;&lt;runtime&gt;30&lt;/runtime&gt;&lt;latestepisode&gt;&lt;number&gt;10x08&lt;/number&gt;&lt;title&gt;Divide and Conquer&lt;/title&gt;&lt;airdate&gt;1996-11-02 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RESPONSE_EPISODEINFO_5481_99x99 {
            get {
                return ResourceManager.GetString("RESPONSE_EPISODEINFO_5481_99x99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Show Results Were Found For &quot;&quot;.
        /// </summary>
        internal static string RESPONSE_EPISODEINFO_999999999_99x99 {
            get {
                return ResourceManager.GetString("RESPONSE_EPISODEINFO_999999999_99x99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///
        ///
        ///&lt;Show&gt;
        ///&lt;name&gt;Wilfred&lt;/name&gt;
        ///&lt;totalseasons&gt;2&lt;/totalseasons&gt;
        ///&lt;Episodelist&gt;
        ///
        ///&lt;EpisodeListResultSeason no=&quot;1&quot;&gt;
        ///&lt;episode&gt;&lt;epnum&gt;1&lt;/epnum&gt;&lt;seasonnum&gt;01&lt;/seasonnum&gt;&lt;prodnum&gt;&lt;/prodnum&gt;&lt;airdate&gt;2007-03-19&lt;/airdate&gt;&lt;link&gt;http://www.tvrage.com/shows/id-15352/episodes/578793&lt;/link&gt;&lt;title&gt;There is a Dog&lt;/title&gt;&lt;/episode&gt;
        ///&lt;episode&gt;&lt;epnum&gt;2&lt;/epnum&gt;&lt;seasonnum&gt;02&lt;/seasonnum&gt;&lt;prodnum&gt;&lt;/prodnum&gt;&lt;airdate&gt;2007-03-26&lt;/airdate&gt;&lt;link&gt;http://www.tvrage.com/shows/id-15352/episodes/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RESPONSE_EPISODELIST_15352 {
            get {
                return ResourceManager.GetString("RESPONSE_EPISODELIST_15352", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///
        ///
        ///&lt;Show&gt;
        ///&lt;name&gt;Kenny&apos;s World&lt;/name&gt;
        ///&lt;totalseasons&gt;1&lt;/totalseasons&gt;
        ///&lt;showid&gt;20260&lt;/showid&gt;
        ///&lt;showlink&gt;http://tvrage.com/shows/id-20260&lt;/showlink&gt;
        ///&lt;started&gt;Sep/10/2008&lt;/started&gt;
        ///&lt;ended&gt;&lt;/ended&gt;
        ///&lt;image&gt;http://images.tvrage.com/shows/21/20260.jpg&lt;/image&gt;
        ///&lt;origin_country&gt;AU&lt;/origin_country&gt;
        ///&lt;status&gt;New Series&lt;/status&gt;
        ///&lt;classification&gt;Reality&lt;/classification&gt;
        ///&lt;genres&gt;&lt;genre&gt;Comedy&lt;/genre&gt;&lt;genre&gt;Educational&lt;/genre&gt;&lt;genre&gt;Housing/Building&lt;/genre&gt;&lt;genre&gt;Travel&lt;/ge [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RESPONSE_EPISODELIST_20260 {
            get {
                return ResourceManager.GetString("RESPONSE_EPISODELIST_20260", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///
        ///
        ///&lt;Show&gt;
        ///&lt;name&gt;Howzat! Kerry Packer&apos;s War&lt;/name&gt;
        ///&lt;totalseasons&gt;1&lt;/totalseasons&gt;
        ///&lt;showid&gt;32517&lt;/showid&gt;
        ///&lt;showlink&gt;http://tvrage.com/shows/id-32517&lt;/showlink&gt;
        ///&lt;started&gt;Aug/19/2012&lt;/started&gt;
        ///&lt;ended&gt;&lt;/ended&gt;
        ///&lt;image&gt;http://images.tvrage.com/shows/33/32517.jpg&lt;/image&gt;
        ///&lt;origin_country&gt;AU&lt;/origin_country&gt;
        ///&lt;status&gt;New Series&lt;/status&gt;
        ///&lt;classification&gt;Mini-Series&lt;/classification&gt;
        ///&lt;genres&gt;&lt;genre&gt;Drama&lt;/genre&gt;&lt;genre&gt;Sports&lt;/genre&gt;&lt;/genres&gt;
        ///&lt;runtime&gt;120&lt;/runtime&gt;
        ///&lt;n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RESPONSE_FULLSHOWINFO_32517 {
            get {
                return ResourceManager.GetString("RESPONSE_FULLSHOWINFO_32517", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Show Results Were Found For &quot;&quot;.
        /// </summary>
        internal static string RESPONSE_FULLSHOWINFO_999999999 {
            get {
                return ResourceManager.GetString("RESPONSE_FULLSHOWINFO_999999999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///
        ///&lt;updates at=&quot;1355598487&quot; found=&quot;214&quot; sorting=&quot;latest_updates&quot; showing=&quot;Last 24H&quot;&gt;
        ///&lt;show&gt;&lt;id&gt;31&lt;/id&gt;&lt;last&gt;-622&lt;/last&gt;&lt;lastepisode&gt;950340&lt;/lastepisode&gt;&lt;/show&gt;
        ///&lt;show&gt;&lt;id&gt;33901&lt;/id&gt;&lt;last&gt;131&lt;/last&gt;&lt;lastepisode&gt;131&lt;/lastepisode&gt;&lt;/show&gt;
        ///&lt;show&gt;&lt;id&gt;3256&lt;/id&gt;&lt;last&gt;1015&lt;/last&gt;&lt;lastepisode&gt;2580&lt;/lastepisode&gt;&lt;/show&gt;
        ///&lt;show&gt;&lt;id&gt;33900&lt;/id&gt;&lt;last&gt;1267&lt;/last&gt;&lt;lastepisode&gt;1281&lt;/lastepisode&gt;&lt;/show&gt;
        ///&lt;/updates&gt;.
        /// </summary>
        internal static string RESPONSE_LASTUPDATES {
            get {
                return ResourceManager.GetString("RESPONSE_LASTUPDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///
        ///&lt;updates at=&apos;1355720878&apos; found=&apos;26&apos; sorting=&apos;latest_updates&apos; showing=&apos;Last 4H&apos;&gt;
        ///&lt;show&gt;&lt;id&gt;31&lt;/id&gt;&lt;last&gt;-622&lt;/last&gt;&lt;lastepisode&gt;950340&lt;/lastepisode&gt;&lt;/show&gt;
        ///&lt;show&gt;&lt;id&gt;33901&lt;/id&gt;&lt;last&gt;131&lt;/last&gt;&lt;lastepisode&gt;131&lt;/lastepisode&gt;&lt;/show&gt;
        ///&lt;show&gt;&lt;id&gt;3256&lt;/id&gt;&lt;last&gt;1015&lt;/last&gt;&lt;lastepisode&gt;2580&lt;/lastepisode&gt;&lt;/show&gt;
        ///&lt;show&gt;&lt;id&gt;33900&lt;/id&gt;&lt;last&gt;1267&lt;/last&gt;&lt;lastepisode&gt;1281&lt;/lastepisode&gt;&lt;/show&gt;
        ///&lt;/updates&gt;.
        /// </summary>
        internal static string RESPONSE_LASTUPDATES_4 {
            get {
                return ResourceManager.GetString("RESPONSE_LASTUPDATES_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///
        ///&lt;updates at=&quot;1355649960&quot; found=&quot;2575&quot; sorting=&quot;latest_updates&quot; showing=&quot;Last 41D, 15H&quot;&gt;
        ///&lt;show&gt;&lt;id&gt;31&lt;/id&gt;&lt;last&gt;-622&lt;/last&gt;&lt;lastepisode&gt;950340&lt;/lastepisode&gt;&lt;/show&gt;
        ///&lt;/updates&gt;.
        /// </summary>
        internal static string RESPONSE_LASTUPDATES_999 {
            get {
                return ResourceManager.GetString("RESPONSE_LASTUPDATES_999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///
        ///&lt;Results&gt;0&lt;/Results&gt;.
        /// </summary>
        internal static string RESPONSE_SEARCH_WILFFERXJD {
            get {
                return ResourceManager.GetString("RESPONSE_SEARCH_WILFFERXJD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///
        ///&lt;Results&gt;
        ///&lt;show&gt;
        ///&lt;showid&gt;15352&lt;/showid&gt;
        ///&lt;name&gt;Wilfred&lt;/name&gt;
        ///&lt;link&gt;http://www.tvrage.com/shows/id-15352&lt;/link&gt;
        ///&lt;country&gt;AU&lt;/country&gt;
        ///&lt;started&gt;2007&lt;/started&gt;
        ///&lt;ended&gt;0&lt;/ended&gt;
        ///&lt;seasons&gt;2&lt;/seasons&gt;
        ///&lt;status&gt;Canceled/Ended&lt;/status&gt;
        ///&lt;classification&gt;Scripted&lt;/classification&gt;
        ///&lt;genres&gt;&lt;genre&gt;Comedy&lt;/genre&gt;&lt;genre&gt;Drama&lt;/genre&gt;&lt;/genres&gt;
        ///&lt;/show&gt;
        ///&lt;show&gt;
        ///&lt;showid&gt;25709&lt;/showid&gt;
        ///&lt;name&gt;Wilfred (US)&lt;/name&gt;
        ///&lt;link&gt;http://www.tvrage.com/Wilfred_US&lt;/link&gt;
        ///&lt;country&gt;US&lt;/c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RESPONSE_SEARCH_WILFRED {
            get {
                return ResourceManager.GetString("RESPONSE_SEARCH_WILFRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///
        ///&lt;Results&gt;0&lt;/Results&gt;.
        /// </summary>
        internal static string RESPONSE_SEARCHFULL_BRACVNKINGBADGA {
            get {
                return ResourceManager.GetString("RESPONSE_SEARCHFULL_BRACVNKINGBADGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///
        ///&lt;Results&gt;
        ///&lt;show&gt;
        ///&lt;showid&gt;18164&lt;/showid&gt;
        ///&lt;name&gt;Breaking Bad&lt;/name&gt;
        ///&lt;link&gt;http://www.tvrage.com/Breaking_Bad&lt;/link&gt;
        ///&lt;country&gt;US&lt;/country&gt;
        ///&lt;started&gt;Jan/20/2008&lt;/started&gt;
        ///&lt;ended&gt;&lt;/ended&gt;
        ///&lt;seasons&gt;5&lt;/seasons&gt;
        ///&lt;status&gt;Final EpisodeListResultSeason&lt;/status&gt;
        ///&lt;runtime&gt;60&lt;/runtime&gt;
        ///&lt;classification&gt;Scripted&lt;/classification&gt;
        ///&lt;genres&gt;&lt;genre&gt;Drama&lt;/genre&gt;&lt;/genres&gt;
        ///&lt;network country=&quot;US&quot;&gt;AMC&lt;/network&gt;
        ///&lt;airtime&gt;22:00&lt;/airtime&gt;
        ///&lt;airday&gt;Sunday&lt;/airday&gt;
        ///&lt;akas&gt;&lt;aka coun [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RESPONSE_SEARCHFULL_BREAKINGBAD {
            get {
                return ResourceManager.GetString("RESPONSE_SEARCHFULL_BREAKINGBAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///
        ///&lt;Showinfo&gt;
        ///&lt;showid&gt;18753&lt;/showid&gt;
        ///&lt;showname&gt;The Inbetweeners&lt;/showname&gt;
        ///&lt;showlink&gt;http://tvrage.com/The_Inbetweeners&lt;/showlink&gt;
        ///&lt;seasons&gt;3&lt;/seasons&gt;
        ///&lt;started&gt;2008&lt;/started&gt;
        ///&lt;startdate&gt;May/01/2008&lt;/startdate&gt;
        ///&lt;ended&gt;&lt;/ended&gt;
        ///&lt;origin_country&gt;UK&lt;/origin_country&gt;
        ///&lt;status&gt;Canceled/Ended&lt;/status&gt;
        ///&lt;classification&gt;Scripted&lt;/classification&gt;
        ///&lt;genres&gt;&lt;genre&gt;Comedy&lt;/genre&gt;&lt;/genres&gt;
        ///&lt;runtime&gt;30&lt;/runtime&gt;
        ///&lt;network  country=&quot;UK&quot;&gt;E4&lt;/network&gt;
        ///&lt;airtime&gt;22:00&lt;/airtime&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RESPONSE_SHOWINFO_18753 {
            get {
                return ResourceManager.GetString("RESPONSE_SHOWINFO_18753", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///
        ///&lt;Showinfo&gt;
        ///&lt;/Showinfo&gt;.
        /// </summary>
        internal static string RESPONSE_SHOWINFO_842999999 {
            get {
                return ResourceManager.GetString("RESPONSE_SHOWINFO_842999999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;shows&gt;
        ///&lt;show&gt;&lt;id&gt;1&lt;/id&gt;&lt;name&gt;Fernwood 2Night&lt;/name&gt;&lt;country&gt;US&lt;/country&gt;&lt;status&gt;2&lt;/status&gt;&lt;/show&gt; 
        ///&lt;show&gt;&lt;id&gt;2&lt;/id&gt;&lt;name&gt;America 2Night&lt;/name&gt;&lt;country&gt;US&lt;/country&gt;&lt;status&gt;2&lt;/status&gt;&lt;/show&gt; 
        ///&lt;show&gt;&lt;id&gt;3&lt;/id&gt;&lt;name&gt;Mary Hartman, Mary Hartman&lt;/name&gt;&lt;country&gt;US&lt;/country&gt;&lt;status&gt;2&lt;/status&gt;&lt;/show&gt; 
        ///&lt;show&gt;&lt;id&gt;4&lt;/id&gt;&lt;name&gt;Sara (1985)&lt;/name&gt;&lt;country&gt;US&lt;/country&gt;&lt;status&gt;2&lt;/status&gt;&lt;/show&gt; 
        ///&lt;show&gt;&lt;id&gt;5&lt;/id&gt;&lt;name&gt;Buffalo Bill&lt;/name&gt;&lt;country&gt;US&lt;/country&gt;&lt;status&gt;2&lt;/status&gt;&lt;/sh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RESPONSE_SHOWLIST {
            get {
                return ResourceManager.GetString("RESPONSE_SHOWLIST", resourceCulture);
            }
        }
    }
}
