//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nRage.Tests.Unit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nRage.Tests.Unit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;show id=&apos;15352&apos;&gt;&lt;name&gt;Wilfred&lt;/name&gt;&lt;link&gt;http://www.tvrage.com/shows/id-15352&lt;/link&gt;&lt;started&gt;2007-03-19&lt;/started&gt;&lt;ended&gt;&lt;/ended&gt;&lt;country&gt;Australia&lt;/country&gt;&lt;status&gt;Canceled/Ended&lt;/status&gt;&lt;classification&gt;Scripted&lt;/classification&gt;&lt;genres&gt;&lt;genre&gt;Comedy&lt;/genre&gt;&lt;genre&gt;Drama&lt;/genre&gt;&lt;/genres&gt;&lt;airtime&gt;Monday&lt;/airtime&gt;&lt;runtime&gt;25&lt;/runtime&gt;&lt;episode&gt;&lt;number&gt;02x05&lt;/number&gt;&lt;title&gt;The Ice Dog Cometh&lt;/title&gt;&lt;airdate&gt;2010-04-05&lt;/airdate&gt;&lt;url&gt;http://www.tvrage.com/shows/id-15352/episodes/1064916984&lt;/url&gt;&lt;/episode&gt;&lt;lateste [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RESPONSE_EPISODEINFO_15352_2x05 {
            get {
                return ResourceManager.GetString("RESPONSE_EPISODEINFO_15352_2x05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///
        ///
        ///&lt;Show&gt;
        ///&lt;name&gt;Wilfred&lt;/name&gt;
        ///&lt;totalseasons&gt;2&lt;/totalseasons&gt;
        ///&lt;Episodelist&gt;
        ///
        ///&lt;Season no=&quot;1&quot;&gt;
        ///&lt;episode&gt;&lt;epnum&gt;1&lt;/epnum&gt;&lt;seasonnum&gt;01&lt;/seasonnum&gt;&lt;prodnum&gt;&lt;/prodnum&gt;&lt;airdate&gt;2007-03-19&lt;/airdate&gt;&lt;link&gt;http://www.tvrage.com/shows/id-15352/episodes/578793&lt;/link&gt;&lt;title&gt;There is a Dog&lt;/title&gt;&lt;/episode&gt;
        ///&lt;episode&gt;&lt;epnum&gt;2&lt;/epnum&gt;&lt;seasonnum&gt;02&lt;/seasonnum&gt;&lt;prodnum&gt;&lt;/prodnum&gt;&lt;airdate&gt;2007-03-26&lt;/airdate&gt;&lt;link&gt;http://www.tvrage.com/shows/id-15352/episodes/578794&lt;/link&gt;&lt;tit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RESPONSE_EPISODELIST_15352 {
            get {
                return ResourceManager.GetString("RESPONSE_EPISODELIST_15352", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///
        ///
        ///&lt;Show&gt;
        ///&lt;name&gt;Wilfred&lt;/name&gt;
        ///&lt;totalseasons&gt;2&lt;/totalseasons&gt;
        ///&lt;showid&gt;15352&lt;/showid&gt;
        ///&lt;showlink&gt;http://tvrage.com/shows/id-15352&lt;/showlink&gt;
        ///&lt;started&gt;Mar/19/2007&lt;/started&gt;
        ///&lt;ended&gt;&lt;/ended&gt;
        ///&lt;image&gt;http://images.tvrage.com/shows/16/15352.jpg&lt;/image&gt;
        ///&lt;origin_country&gt;AU&lt;/origin_country&gt;
        ///&lt;status&gt;Canceled/Ended&lt;/status&gt;
        ///&lt;classification&gt;Scripted&lt;/classification&gt;
        ///&lt;genres&gt;&lt;genre&gt;Comedy&lt;/genre&gt;&lt;genre&gt;Drama&lt;/genre&gt;&lt;/genres&gt;
        ///&lt;runtime&gt;25&lt;/runtime&gt;
        ///&lt;network country=&quot;AU&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RESPONSE_FULLSHOWINFO_15352 {
            get {
                return ResourceManager.GetString("RESPONSE_FULLSHOWINFO_15352", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///
        ///&lt;Results&gt;0&lt;/Results&gt;.
        /// </summary>
        internal static string RESPONSE_SEARCH_WILFFERXJD {
            get {
                return ResourceManager.GetString("RESPONSE_SEARCH_WILFFERXJD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///
        ///&lt;Results&gt;
        ///&lt;show&gt;
        ///&lt;showid&gt;15352&lt;/showid&gt;
        ///&lt;name&gt;Wilfred&lt;/name&gt;
        ///&lt;link&gt;http://www.tvrage.com/shows/id-15352&lt;/link&gt;
        ///&lt;country&gt;AU&lt;/country&gt;
        ///&lt;started&gt;2007&lt;/started&gt;
        ///&lt;ended&gt;0&lt;/ended&gt;
        ///&lt;seasons&gt;2&lt;/seasons&gt;
        ///&lt;status&gt;Canceled/Ended&lt;/status&gt;
        ///&lt;classification&gt;Scripted&lt;/classification&gt;
        ///&lt;genres&gt;&lt;genre&gt;Comedy&lt;/genre&gt;&lt;genre&gt;Drama&lt;/genre&gt;&lt;/genres&gt;
        ///&lt;/show&gt;
        ///&lt;show&gt;
        ///&lt;showid&gt;25709&lt;/showid&gt;
        ///&lt;name&gt;Wilfred (US)&lt;/name&gt;
        ///&lt;link&gt;http://www.tvrage.com/Wilfred_US&lt;/link&gt;
        ///&lt;country&gt;US&lt;/c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RESPONSE_SEARCH_WILFRED {
            get {
                return ResourceManager.GetString("RESPONSE_SEARCH_WILFRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///
        ///&lt;Results&gt;
        ///&lt;show&gt;
        ///&lt;showid&gt;15352&lt;/showid&gt;
        ///&lt;name&gt;Wilfred&lt;/name&gt;
        ///&lt;link&gt;http://www.tvrage.com/shows/id-15352&lt;/link&gt;
        ///&lt;country&gt;AU&lt;/country&gt;
        ///&lt;started&gt;Mar/19/2007&lt;/started&gt;
        ///&lt;ended&gt;&lt;/ended&gt;
        ///&lt;seasons&gt;2&lt;/seasons&gt;
        ///&lt;status&gt;Canceled/Ended&lt;/status&gt;
        ///&lt;runtime&gt;25&lt;/runtime&gt;
        ///&lt;classification&gt;Scripted&lt;/classification&gt;
        ///&lt;genres&gt;&lt;genre&gt;Comedy&lt;/genre&gt;&lt;genre&gt;Drama&lt;/genre&gt;&lt;/genres&gt;
        ///&lt;network country=&quot;AU&quot;&gt;SBS&lt;/network&gt;
        ///&lt;airtime&gt;12:00&lt;/airtime&gt;
        ///&lt;airday&gt;Monday&lt;/airday&gt;
        ///&lt;/show&gt;
        ///&lt;sh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RESPONSE_SEARCHFULL_WILFRED {
            get {
                return ResourceManager.GetString("RESPONSE_SEARCHFULL_WILFRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///
        ///&lt;Showinfo&gt;
        ///&lt;showid&gt;15352&lt;/showid&gt;
        ///&lt;showname&gt;Wilfred&lt;/showname&gt;
        ///&lt;showlink&gt;http://tvrage.com/shows/id-15352&lt;/showlink&gt;
        ///&lt;seasons&gt;2&lt;/seasons&gt;
        ///&lt;started&gt;2007&lt;/started&gt;
        ///&lt;startdate&gt;Mar/19/2007&lt;/startdate&gt;
        ///&lt;ended&gt;&lt;/ended&gt;
        ///&lt;origin_country&gt;AU&lt;/origin_country&gt;
        ///&lt;status&gt;Canceled/Ended&lt;/status&gt;
        ///&lt;classification&gt;Scripted&lt;/classification&gt;
        ///&lt;genres&gt;&lt;genre&gt;Comedy&lt;/genre&gt;&lt;genre&gt;Drama&lt;/genre&gt;&lt;/genres&gt;
        ///&lt;runtime&gt;25&lt;/runtime&gt;
        ///&lt;network  country=&quot;AU&quot;&gt;SBS&lt;/network&gt;
        ///&lt;airtime&gt;12:00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RESPONSE_SHOWINFO_15352 {
            get {
                return ResourceManager.GetString("RESPONSE_SHOWINFO_15352", resourceCulture);
            }
        }
    }
}
