//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nRage.Tests.Unit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TheTVDB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TheTVDB() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nRage.Tests.Unit.Properties.TheTVDB", typeof(TheTVDB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//IETF//DTD HTML 2.0//EN&quot;&gt;
        ///&lt;html&gt;&lt;head&gt;
        ///&lt;title&gt;404 Not Found&lt;/title&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        /////&lt;![CDATA[
        ///window.__CF=window.__CF||{};window.__CF.AJS={&quot;ga_key&quot;:{&quot;ua&quot;:&quot;UA-9131861-1&quot;,&quot;ga_bs&quot;:&quot;2&quot;}};
        /////]]&gt;
        ///&lt;/script&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        /////&lt;![CDATA[
        ///try{if (!window.CloudFlare) { var CloudFlare=[{verbose:0,p:0,byc:0,owlid:&quot;cf&quot;,mirage:{responsive:0,lazy:0},oracle:0,paths:{cloudflare:&quot;/cdn-cgi/nexp/abv=1870252173/&quot;},atok:&quot;bd59c2ce05cdbf8ec4c7ca4c564b57d5&quot;,zone:&quot;th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RESPONSE_EPISODELIST_1 {
            get {
                return ResourceManager.GetString("RESPONSE_EPISODELIST_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;Data&gt;&lt;Series&gt;
        ///  &lt;id&gt;81189&lt;/id&gt;
        ///  &lt;Actors&gt;|Bryan Cranston|Aaron Paul|Dean Norris|RJ Mitte|Betsy Brandt|Anna Gunn|Christopher Cousins|Steven Michael Quezada|Jonathan Banks|Giancarlo Esposito|Bob Odenkirk|&lt;/Actors&gt;
        ///  &lt;Airs_DayOfWeek&gt;Sunday&lt;/Airs_DayOfWeek&gt;
        ///  &lt;Airs_Time&gt;10:00 PM&lt;/Airs_Time&gt;
        ///  &lt;ContentRating&gt;TV-MA&lt;/ContentRating&gt;
        ///  &lt;FirstAired&gt;2008-01-20&lt;/FirstAired&gt;
        ///  &lt;Genre&gt;|Drama|&lt;/Genre&gt;
        ///  &lt;IMDB_ID&gt;tt0903747&lt;/IMDB_ID&gt;
        ///  &lt;Language&gt;en&lt;/Language&gt;
        ///  &lt;Network&gt;AM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RESPONSE_EPISODELIST_81189 {
            get {
                return ResourceManager.GetString("RESPONSE_EPISODELIST_81189", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;Data&gt;
        ///&lt;Series&gt;
        ///&lt;seriesid&gt;81189&lt;/seriesid&gt;
        ///&lt;language&gt;en&lt;/language&gt;
        ///&lt;SeriesName&gt;Breaking Bad&lt;/SeriesName&gt;
        ///&lt;banner&gt;graphical/81189-g13.jpg&lt;/banner&gt;
        ///&lt;Overview&gt;Walter White, a struggling high school chemistry teacher is diagnosed with advanced lung cancer. He turns to a life of crime, producing and selling methamphetamine accompanied by a former student, Jesse Pinkman with the aim of securing his family&apos;s financial future before he dies.&lt;/Overview&gt;
        ///&lt;FirstAired&gt;200 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RESPONSE_GETSERIES_BREAKINGBAD {
            get {
                return ResourceManager.GetString("RESPONSE_GETSERIES_BREAKINGBAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;Mirrors&gt;
        ///  &lt;Mirror&gt;
        ///    &lt;id&gt;1&lt;/id&gt;
        ///    &lt;mirrorpath&gt;http://thetvdb.com&lt;/mirrorpath&gt;
        ///    &lt;typemask&gt;7&lt;/typemask&gt;
        ///  &lt;/Mirror&gt;
        ///&lt;/Mirrors&gt;.
        /// </summary>
        internal static string RESPONSE_MIRRORS {
            get {
                return ResourceManager.GetString("RESPONSE_MIRRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//IETF//DTD HTML 2.0//EN&quot;&gt;
        ///&lt;html&gt;&lt;head&gt;
        ///&lt;title&gt;404 Not Found&lt;/title&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        /////&lt;![CDATA[
        ///window.__CF=window.__CF||{};window.__CF.AJS={&quot;ga_key&quot;:{&quot;ua&quot;:&quot;UA-9131861-1&quot;,&quot;ga_bs&quot;:&quot;2&quot;}};
        /////]]&gt;
        ///&lt;/script&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        /////&lt;![CDATA[
        ///try{if (!window.CloudFlare) { var CloudFlare=[{verbose:0,p:0,byc:0,owlid:&quot;cf&quot;,mirage:{responsive:0,lazy:0},oracle:0,paths:{cloudflare:&quot;/cdn-cgi/nexp/abv=1870252173/&quot;},atok:&quot;bd59c2ce05cdbf8ec4c7ca4c564b57d5&quot;,zone:&quot;th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RESPONSE_SERIESINFO_1 {
            get {
                return ResourceManager.GetString("RESPONSE_SERIESINFO_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;Data&gt;
        ///  &lt;Series&gt;
        ///    &lt;id&gt;81189&lt;/id&gt;
        ///    &lt;Actors&gt;|Bryan Cranston|Aaron Paul|Dean Norris|RJ Mitte|Betsy Brandt|Anna Gunn|Christopher Cousins|Steven Michael Quezada|Jonathan Banks|Giancarlo Esposito|Bob Odenkirk|&lt;/Actors&gt;
        ///    &lt;Airs_DayOfWeek&gt;Sunday&lt;/Airs_DayOfWeek&gt;
        ///    &lt;Airs_Time&gt;10:00 PM&lt;/Airs_Time&gt;
        ///    &lt;ContentRating&gt;TV-MA&lt;/ContentRating&gt;
        ///    &lt;FirstAired&gt;2008-01-20&lt;/FirstAired&gt;
        ///    &lt;Genre&gt;|Drama|&lt;/Genre&gt;
        ///    &lt;IMDB_ID&gt;tt0903747&lt;/IMDB_ID&gt;
        ///    &lt;Language&gt;en&lt;/La [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RESPONSE_SERIESINFO_81189 {
            get {
                return ResourceManager.GetString("RESPONSE_SERIESINFO_81189", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;Items&gt;
        ///&lt;Time&gt;1355812429&lt;/Time&gt;
        ///&lt;Series&gt;70327&lt;/Series&gt;
        ///&lt;Series&gt;70328&lt;/Series&gt;
        ///&lt;Series&gt;70329&lt;/Series&gt;
        ///&lt;Series&gt;70330&lt;/Series&gt;
        ///&lt;Series&gt;70331&lt;/Series&gt;
        ///&lt;Series&gt;257855&lt;/Series&gt;
        ///&lt;Series&gt;70333&lt;/Series&gt;
        ///&lt;Series&gt;70334&lt;/Series&gt;
        ///&lt;Series&gt;70335&lt;/Series&gt;
        ///&lt;Series&gt;70336&lt;/Series&gt;
        ///&lt;Series&gt;70337&lt;/Series&gt;
        ///&lt;Series&gt;70338&lt;/Series&gt;
        ///&lt;Series&gt;257843&lt;/Series&gt;
        ///&lt;/Items&gt;.
        /// </summary>
        internal static string RESPONSE_UPDATES_ALL_1355812429 {
            get {
                return ResourceManager.GetString("RESPONSE_UPDATES_ALL_1355812429", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;Items&gt;
        ///&lt;Time&gt;1355786893&lt;/Time&gt;
        ///&lt;/Items&gt;.
        /// </summary>
        internal static string RESPONSE_UPDATES_NONE {
            get {
                return ResourceManager.GetString("RESPONSE_UPDATES_NONE", resourceCulture);
            }
        }
    }
}
