//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nRage.Tests.Unit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TheTVDB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TheTVDB() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nRage.Tests.Unit.Properties.TheTVDB", typeof(TheTVDB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;Data&gt;
        ///&lt;Series&gt;
        ///&lt;seriesid&gt;81189&lt;/seriesid&gt;
        ///&lt;language&gt;en&lt;/language&gt;
        ///&lt;SeriesName&gt;Breaking Bad&lt;/SeriesName&gt;
        ///&lt;banner&gt;graphical/81189-g13.jpg&lt;/banner&gt;
        ///&lt;Overview&gt;Walter White, a struggling high school chemistry teacher is diagnosed with advanced lung cancer. He turns to a life of crime, producing and selling methamphetamine accompanied by a former student, Jesse Pinkman with the aim of securing his family&apos;s financial future before he dies.&lt;/Overview&gt;
        ///&lt;FirstAired&gt;200 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RESPONSE_GETSERIES_BREAKINGBAD {
            get {
                return ResourceManager.GetString("RESPONSE_GETSERIES_BREAKINGBAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;Mirrors&gt;
        ///  &lt;Mirror&gt;
        ///    &lt;id&gt;1&lt;/id&gt;
        ///    &lt;mirrorpath&gt;http://thetvdb.com&lt;/mirrorpath&gt;
        ///    &lt;typemask&gt;7&lt;/typemask&gt;
        ///  &lt;/Mirror&gt;
        ///&lt;/Mirrors&gt;.
        /// </summary>
        internal static string RESPONSE_MIRRORS {
            get {
                return ResourceManager.GetString("RESPONSE_MIRRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;Items&gt;
        ///&lt;Time&gt;1355786893&lt;/Time&gt;
        ///&lt;/Items&gt;.
        /// </summary>
        internal static string RESPONSE_UPDATES_NONE {
            get {
                return ResourceManager.GetString("RESPONSE_UPDATES_NONE", resourceCulture);
            }
        }
    }
}
